// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	listProjects: () => typedError<Project[], string>(__TAURI_INVOKE("list_projects")),
	getProject: (id: string) => typedError<Project, string>(__TAURI_INVOKE("get_project", { id })),
	saveProject: (project: Project) => typedError<null, string>(__TAURI_INVOKE("save_project", { project })),
	deleteProject: (id: string) => typedError<null, string>(__TAURI_INVOKE("delete_project", { id })),
	validateScenario: (project: Project) => typedError<string[], string>(__TAURI_INVOKE("validate_scenario", { project })),
	preflight: (projectId: string | null) => typedError<PreflightReport, string>(__TAURI_INVOKE("preflight", { projectId })),
	cpuModel: () => typedError<string, string>(__TAURI_INVOKE("cpu_model")),
	gpuModel: () => typedError<string, string>(__TAURI_INVOKE("gpu_model")),
	listPowerPlans: () => typedError<PowerPlan[], string>(__TAURI_INVOKE("list_power_plans")),
	readCs2LaunchOptions: () => typedError<string, string>(__TAURI_INVOKE("read_cs2_launch_options")),
	getConfig: () => typedError<Config, string>(__TAURI_INVOKE("get_config")),
	saveConfig: (config: Config) => typedError<null, string>(__TAURI_INVOKE("save_config", { config })),
	listCatalogTweaks: () => typedError<CatalogEntry[], string>(__TAURI_INVOKE("list_catalog_tweaks")),
	startRun: (projectId: string, dryRun: boolean) => typedError<string, string>(__TAURI_INVOKE("start_run", { projectId, dryRun })),
	sendControl: (msg: ControlMsg) => typedError<null, string>(__TAURI_INVOKE("send_control", { msg })),
	getResults: (runId: string) => typedError<RunResults, string>(__TAURI_INVOKE("get_results", { runId })),
	listResults: (projectId: string) => typedError<RunSummary[], string>(__TAURI_INVOKE("list_results", { projectId })),
	getRunSnapshot: () => typedError<{
	schema_version: string,
	run_id: string,
	project_id: string,
	phase: Phase,
	current_scenario: string | null,
	completed_scenarios: string[],
	revision: number,
} | null, string>(__TAURI_INVOKE("get_run_snapshot")),
	rollbackNow: () => typedError<RevertReport, string>(__TAURI_INVOKE("rollback_now")),
	emergencyRollback: () => typedError<RevertReport[], string>(__TAURI_INVOKE("emergency_rollback")),
	openDataDir: () => typedError<null, string>(__TAURI_INVOKE("open_data_dir")),
	revealRestoreBat: () => typedError<null, string>(__TAURI_INVOKE("reveal_restore_bat")),
};

/* Types */
export type AffinityCpuPayload = {
	mode: AffinityMode,
	mask_hex?: string | null,
};

export type AffinityMode = "pcore_only" | "ccd0" | "exclude_core0" | "explicit_mask";

/**  The baseline "scenario" — no modules applied. */
export type Baseline = {
	name: string,
	description: string,
};

export type CatalogEntry = {
	id: string,
	name: string,
	category: string,
	kind: string,
	description: string,
	available_in: string,
	/**
	 *  A ready-to-use `Module` JSON value (matches `Module`'s own
	 *  `#[serde(tag = "type")]` shape) — the builder can drop this
	 *  straight into a scenario's `modules` array and let the user tweak
	 *  specific fields (e.g. `affinityMask` for `explicit_mask`) from
	 *  there, rather than re-deriving the whole shape client-side.
	 * 
	 *  Exported to TypeScript as `unknown` (specta-typescript's own documented
	 *  per-field escape hatch for opaque/dynamic JSON, `specta_typescript::Unknown`
	 *  -- deliberately not narrowing it further: this field is intentionally
	 *  untyped, and specta's own `serde_json::Value` structural export hits
	 *  its BigInt-forbidden guard on `serde_json::Number`'s internal i64/u64
	 *  variant, which nothing in this crate's own types can fix directly).
	 */
	module_template: unknown,
	/**
	 *  `true` if a scenario may contain at most one module of this entry's
	 *  `kind` (e.g. `power_plan` -- a scenario targets exactly one power
	 *  plan, so a second one is never meaningful). Enforced by
	 *  `mutation::conflict_check`. Defaults to `false` so every other,
	 *  already-shipped catalog entry needs no change.
	 */
	singleton?: boolean,
};

export type Check = {
	id: string,
	status: CheckStatus,
	detail: string,
};

export type CheckStatus = "pass" | "warn" | "block" | "deferred";

export type Config = {
	presentmon_path?: string,
	default_warmup_loops?: number,
	default_measure_loops?: number,
	default_capture_seconds?: number,
	dry_run_default?: boolean,
	last_known_cs2_build_id?: string | null,
	/**  HWiNFO64.exe's bundled install location (docs/superpowers/specs/2026-09-05-bundled-tools-alpha-install-design.md §2). */
	hwinfo_path?: string | null,
	/**  On by default -- see `default_thermal_cooldown_enabled`. */
	thermal_cooldown_enabled?: boolean,
};

export type ControlMsg = "Pause" | "Resume" | "Abort" | 
/**
 *  Answers an `OperatorPrompt` — e.g. "I've closed Steam" / "I've
 *  reopened Steam" for the launch-args-changed manual-restart flow
 *  (`docs/superpowers/specs/2026-09-01-m1-benchmark-engine-design.md` §7.2 step 2). The prompt's own text distinguishes which
 *  question is being answered; `execute` polls `steam_status()` itself
 *  rather than trusting this message's timing exactly (a user might
 *  click "done" before Steam has actually finished starting).
 */
"OperatorAcknowledged";

/**
 *  Which game-synchronisation tier produced a run's captures
 *  (`docs/03-functional-spec.md` §4).
 */
export type DetectionTier = "log_tail" | "fixed_window";

export type EngineEvent = { type: "PhaseChanged"; phase: Phase } | { type: "LogLine"; text: string } | { type: "IterationStarted"; kind: IterationKind; index: number } | { type: "CapturePending" } | { type: "CaptureResumed" } | 
/**
 *  Bracket ONLY the real PresentMon capture call itself (not the settle
 *  sleep before it, not the post-capture wait for the benchmark-ended
 *  marker — those stay covered by `CapturePending`/`CaptureResumed`,
 *  whose wider window exists for the webview-suspend feature). Sent
 *  once per measure iteration; never sent for a warmup iteration
 *  (warmup never captures).
 */
{ type: "RecordingStarted" } | { type: "RecordingStopped" } | { type: "IterationComplete"; metrics: Metrics } | { type: "ScenarioComplete"; result: ScenarioResult } | { type: "OperatorPrompt"; text: string } | { type: "RunComplete"; run_id: string } | { type: "RunFailed"; reason: string } | { type: "RollbackProgress"; reverted: number };

export type Hive = "HKLM" | "HKCU";

/**  Whether an iteration is a (never captured) warmup or a measured one. */
export type IterationKind = "warmup" | "measure";

/**
 *  One metric's plain percent delta (scenario mean vs. baseline mean) --
 *  descriptive only. WCPS v3's `Verdict` is a single holistic call across
 *  all 6 metrics together (Hotelling's T² + TOST), not a per-metric
 *  significance test the way WCPS v2's now-deleted `MetricComparison` used
 *  to attach one CI+verdict per metric.
 */
export type MetricDelta = {
	metric: string,
	delta_pct: number | null,
};

/**  Metrics for one measurement iteration (or an aggregate over several). */
export type Metrics = {
	avg_fps: number | null,
	median_fps: number | null,
	p1_fps: number | null,
	p01_fps: number | null,
	frame_time_mean_ms: number | null,
	frame_time_stddev_ms: number | null,
	frame_time_cv: number | null,
	/**
	 *  WCPS v3's pacing-aware frame-time CV: RMS deviation from a
	 *  time-windowed backward moving average (not the whole-capture mean),
	 *  normalized by the whole-capture mean frame time. See
	 *  `stats::v3::metrics::adaptive_frame_time_cv`'s own doc comment for
	 *  the full derivation.
	 */
	adaptive_frame_time_cv: number | null,
	/**
	 *  WCPS v3's stutter-count percentage: the fraction of frames whose
	 *  frame time exceeds `k=2.0` times the capture's mean frame time. See
	 *  `stats::v3::metrics::stutter_count_pct`.
	 */
	stutter_count_pct: number | null,
	/**
	 *  WCPS v3's animation-timing-error metric, from PresentMon's own
	 *  `MsAnimationError` column. `None` when every frame's value was `NA`
	 *  (only expected for a capture with essentially zero usable frames —
	 *  a real capture always has this `Some`, since only frame 0 is ever
	 *  `NA`). See `stats::v3::metrics::mean_abs_animation_error_ms`.
	 */
	mean_abs_animation_error_ms: number | null,
	gpu_busy_ms: number | null,
	bottleneck_ratio: number | null,
	render_latency_ms: number | null,
	/**
	 *  The most common raw `PresentMode` string across this iteration's
	 *  frames (see `capture::present_mode`).
	 */
	dominant_present_mode?: string,
	/**  `true` only if every frame shared the exact same `PresentMode`. */
	present_mode_consistent?: boolean,
	/**
	 *  Set when `dominant_present_mode` indicates the compositor was in
	 *  the frame path (see `PresentModeCategory::is_compositor_bypassed`)
	 *  — a likely benchmarking misconfiguration (e.g. CS2 not set to
	 *  exclusive Fullscreen), surfaced directly in the report rather than
	 *  left for the user to infer from raw numbers.
	 */
	present_mode_warning?: string | null,
};

/**
 *  One tweak. Internally tagged by `type`. Any unrecognised `type` deserializes
 *  to [`Module::Unsupported`], which [`Module::require_m1_supported`] rejects.
 */
export type Module = {
	type: "registry",
} & RegistryPayload | ({ type: "powercfg"; sub: string; setting: string; value: number }) & { args?: never } | {
	type: "power_plan",
} & PowerPlanPayload | {
	type: "affinity_cpu",
} & AffinityCpuPayload | ({ type: "launch_args"; args: string }) & { setting?: never; sub?: never; value?: never } | ({ type: "unsupported" }) & { args?: never; setting?: never; sub?: never; value?: never };

export type Phase = { kind: "preflight" } | { kind: "snapshot" } | { kind: "thermal_baseline" } | { kind: "baseline" } | { kind: "scenario"; id: string } | { kind: "rollback" } | { kind: "report" };

export type PowerPlan = {
	guid: string,
	name: string,
	active: boolean,
};

export type PowerPlanPayload = {
	plan_guid: string,
	friendly_name?: string | null,
	create_if_missing?: boolean,
};

export type PreflightReport = {
	checks: Check[],
};

/**  A benchmark project: settings, a baseline, and 1..N scenarios. */
export type Project = {
	schema_version: string,
	id: string,
	name: string,
	description: string,
	created_at: string,
	settings: Settings,
	baseline: Baseline,
	scenarios?: Scenario[],
};

export type RegType = "DWORD" | "QWORD" | "SZ" | "BINARY" | 
/**
 *  `REG_EXPAND_SZ`. `#[serde(rename)]` because plain `rename_all =
 *  "UPPERCASE"` would produce `EXPANDSZ`, not the `EXPAND_SZ` the
 *  catalog and `docs/08-security-model.md` §5 use.
 */
"EXPAND_SZ" | 
/**
 *  `REG_MULTI_SZ`; see [`ExpandSz`](Self::ExpandSz)'s doc comment for why
 *  this needs an explicit rename too.
 */
"MULTI_SZ";

export type RegistryPayload = {
	hive: Hive,
	subkey: string,
	value_name: string,
	value_type: RegType,
	/**
	 *  The registry value's actual data -- deliberately untyped (its shape
	 *  depends on `value_type`: a DWORD needs a number, a SZ needs a
	 *  string, etc.). Exported to TypeScript as `unknown`, same reasoning and
	 *  same specta-typescript escape hatch as `CatalogEntry.module_template`.
	 */
	value: unknown,
};

/**
 *  `Serialize` is required here (not just for internal engine use) because
 *  this type crosses the Tauri IPC boundary as a command return value
 *  (`rollback_now`/`emergency_rollback` in `src-tauri`). `specta::Type` is
 *  required for the same reason — `tauri-specta`'s export needs it to
 *  generate this type's real TypeScript shape, not just accept it as an
 *  opaque return value.
 */
export type RevertReport = {
	reverted: number,
	verify_failures: string[],
};

export type RunResults = {
	schema_version: string,
	run_id: string,
	project_id: string,
	completed_at: string,
	detection_tier: DetectionTier,
	baseline: ScenarioResult,
	scenarios: ScenarioResult[],
};

export type RunState = {
	schema_version: string,
	run_id: string,
	project_id: string,
	phase: Phase,
	current_scenario: string | null,
	completed_scenarios: string[],
	revision: number,
};

/**
 *  A lightweight summary of a `RunResults` for a results-history listing UI
 *  -- everything it needs without shipping every iteration's raw `Metrics`.
 */
export type RunSummary = {
	run_id: string,
	project_id: string,
	completed_at: string,
	scenario_count: number,
	winner_name: string | null,
	winner_wcps: number | null,
};

/**  One test scenario: a named set of modules applied against the baseline. */
export type Scenario = {
	id: string,
	name: string,
	description: string,
	enabled?: boolean,
	modules?: Module[],
};

/**
 *  `verdict` has no meaningful value for the baseline's own `ScenarioResult`
 *  -- by convention, `run_scenario` sets it to `Verdict::ConfirmedSame` for
 *  the baseline entry, matching "a thing compared against itself is always
 *  the same"; the frontend should treat the baseline row's verdict/wcps as
 *  decorative, same as today's UI already does by showing "Baseline"/"—"
 *  instead of reading those fields for that row.
 */
export type ScenarioResult = {
	scenario_id: string,
	name: string,
	is_baseline: boolean,
	aggregated: Metrics,
	per_iteration: Metrics[],
	metric_deltas: MetricDelta[],
	wcps: number | null,
	verdict: Verdict,
};

/**
 *  Run parameters. Every field has a spec default so an empty `{}` deserializes.
 * 
 *  `warmup_loops` is a placeholder calibrated in
 *  `docs/superpowers/specs/2026-09-01-m1-benchmark-engine-design.md` §11a;
 *  `measure_loops` must be one of `stats::v3::CALIBRATED_N_LADDER`'s
 *  calibrated values (enforced by [`Settings::validate`]).
 */
export type Settings = {
	schema_version?: string,
	measure_loops?: number,
	warmup_loops?: number,
	capture_seconds?: number,
	map_id?: string,
	watchdog_seconds?: number,
	netcon_port?: number | null,
};

export type Verdict = "better" | "worse" | "no_measurable_difference" | 
/**
 *  WCPS v3's OR-of-2-Hotelling / AND-of-2-TOST combined verdict when
 *  TOST equivalence holds on both the throughput and pacing axes --
 *  `study/research/wcps-v3-design.md` §6's own plan: split
 *  `NoMeasurableDifference` into two rather than grow a binary enum to
 *  three. Never produced by WCPS v2's `compare_metric`
 *  (`stats/significance.rs`) -- that's still a per-metric CI check with
 *  no equivalence-testing concept, only `stats::v3::evaluate_verdict`
 *  (`docs/superpowers/plans/2026-09-04-wcps-v3-score-and-verdict.md`)
 *  produces this variant.
 */
"confirmed_same" | 
/**
 *  WCPS v3's combined verdict when neither Hotelling flags `Different`
 *  nor TOST confirms equivalence on both axes -- the other half of the
 *  `NoMeasurableDifference` split. Same non-production note as
 *  `ConfirmedSame` above.
 */
"inconclusive";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

